#!/bin/sh -e

cd $(dirname $0)
WORKDIR=$(pwd)

mkdir -p .build/
cd .build

if ! cd nginx-* >/dev/null 2>&1; then
	curl -L http://nginx.org/download/nginx-1.10.3.tar.gz > _nginx-1.10.3.tar.gz
	tar xzvf _nginx-1.10.3.tar.gz && cd nginx-*
fi


if ! ./configure --add-dynamic-module=../../module --user=nginx --group=nginx \
	--with-ipv6 --with-file-aio --with-pcre-jit --with-http_dav_module --with-http_ssl_module \
	--with-http_stub_status_module --with-http_gzip_static_module --with-http_v2_module \
	--with-http_auth_request_module --with-mail --with-mail_ssl_module \
	--with-cc-opt="-Wno-error"; then
	echo "Failed to find configure modules for nginx. Did you forget to run 'apt-get build-dep nginx'?"
	exit 1
fi

make modules 


rm -rf ../../bin && mkdir ../../bin
cp objs/ngx_http_webshell_module.so ../../bin/ngx_http_webshell_alpine-x86_64.so

cat <<EOF > Dockerfile.alpine-tmp
FROM alpine:3.4
MAINTAINER CUI Wei <ghostplant@qq.com>

ENV LANG en_US.UTF-8

RUN apk --update add nginx openssl tmux openssh-client screen && rm -rf /var/cache/apk
ADD static /opt/static
ADD wsh-run /opt/wsh-run
ADD module/www.cfg.in /opt/module/www.cfg.in
ADD bin/ngx_http_webshell_alpine-x86_64.so /opt/bin/ngx_http_webshell_alpine-x86_64.so
RUN ln -s /usr/sbin /opt/bin/sbin && sed -i '1 i\\load_module /opt/bin/ngx_http_webshell_alpine-x86_64.so;' /opt/module/www.cfg.in

EXPOSE 8080/tcp
CMD "/opt/wsh-run"
EOF

sudo docker build -t ghostplant/webshell -f Dockerfile.alpine-tmp ../..

echo
echo "============================================================="
echo "  Build Output: ghostplant/webshell:latest"
echo
echo "  [RUN] docker run -it --rm --net=host ghostplant/webshell"
echo "============================================================="
